name: Mirror to GitCode
on: [push]
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.GITCODE_SSH_PRIVATE_KEY }}
    - name: Mirror Sync
      run: |
        git remote add gitcode git@gitcode.com:swj2323/zby.git
        git push --mirror gitcode
