name: Auto-Download
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # 每天 UTC 18 点执行

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库
        run: git clone https://github.com/swj2323/zby.git repo

      - name: 进入仓库目录
        run: cd repo

      - name: 下载文件
        run: wget -O ALL.m3u8 "https://iptv.wwkejishe.top/ALL.m3u8"

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "swj2323"
          git config --global user.email "656556071@qq.com"

      - name: 提交文件
        run: |
          git add ALL.m3u8
          git commit -m "Update file"
          git push origin $(git rev-parse --abbrev-ref HEAD)
