name: Auto-Download
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # 每天 UTC 18 点执行

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 设置工作目录
        run: mkdir -p Download

      - name: 下载文件
        run: wget -O Download/ALL.m3u8 "https://iptv.wwkejishe.top/ALL.m3u8"
